#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

golangci-lint run

            go fmt .
            golangci-lint run
    
go test -v ./...
golangci-lint run

            go fmt .
     go test -v ./..
    
golangci-lint run
